name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: delete to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob delete-batch --account-name maraudersatsea  --auth-mode key -s '$web'
           
    - name: Upload website to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name maraudersatsea  --auth-mode key -d '$web' -s ./website_test

    # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
